/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.VFPK.Visao;

import com.VFPK.Modelo.Gasto;
import com.VFPK.Modelo.TipoDeGastos;
import com.VFPK.Modelo.Veiculo;
import com.VFPK.Persistencia.gastosDao;
import com.VFPK.Persistencia.tipoDeGastosDao;
import com.VFPK.Persistencia.veiculoDao;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ageuv
 */
public class TelaGrafico extends javax.swing.JInternalFrame {
    public DefaultCategoryDataset barra = new DefaultCategoryDataset();
    veiculoDao veiculoDao = new veiculoDao();
    tipoDeGastosDao tipoGastosDao = new tipoDeGastosDao();
    gastosDao gastosDao = new gastosDao();
    /**
     * Creates new form TelaGrafico
     */
    private void imprimirDadosNaComboBoxVeiculo(ArrayList<Veiculo> listaDeVeiculos){
            try{
        jComboBoxGrafVeiculo.removeAllItems();
        Iterator<Veiculo> lista = listaDeVeiculos.iterator();
        
        while(lista.hasNext()){
            Veiculo aux = lista.next();
            jComboBoxGrafVeiculo.addItem(aux.getPlaca());
        }
    }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    }
    private void imprimirDadosNaComboBoxTipoGasto(ArrayList<TipoDeGastos> listaDeTiposDeGasto){
            try{
        jComboBoxGrafTipoGasto.removeAllItems();
        Iterator<TipoDeGastos> lista = listaDeTiposDeGasto.iterator();
        
        while(lista.hasNext()){
            TipoDeGastos aux = lista.next();
            jComboBoxGrafTipoGasto.addItem(aux.getNomeTipoDeGasto());
        }
    }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    }
    private void imprimirDadosNaComboBoxAno(ArrayList<Gasto> listaDeGasto){
            try{
        jComboBoxGrafAno.removeAllItems();
        Iterator<Gasto> lista = listaDeGasto.iterator();
        
        while(lista.hasNext()){
            Gasto aux = lista.next();
            jComboBoxGrafAno.addItem(aux.getData().getYear() + "");
        }
    }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    }
    private void imprimirDadosNaComboBoxMes(ArrayList<Gasto> listaDeGasto){
            try{
        jComboBoxGrafMes.removeAllItems();
        Iterator<Gasto> lista = listaDeGasto.iterator();
        
        while(lista.hasNext()){
            Gasto aux = lista.next();
            jComboBoxGrafMes.addItem(aux.getData().getMonth() + "");
        }
    }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    }
    
    public TelaGrafico() throws PropertyVetoException {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        setMaximum(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        criarGrafico();
        
    }
    public void criarGrafico(){
        barra.setValue(1400, "China", "");
        barra.setValue(1200, "India", "");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFreeChart grafico = ChartFactory.createBarChart3D("A", "B", "C", barra, PlotOrientation.VERTICAL, true, true, false);
        jPanelbarra = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxGrafVeiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGrafAno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxGrafTipoGasto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxGrafMes = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbarra = new ChartPanel(grafico);
        jPanelbarra.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelbarraLayout = new javax.swing.GroupLayout(jPanelbarra);
        jPanelbarra.setLayout(jPanelbarraLayout);
        jPanelbarraLayout.setHorizontalGroup(
            jPanelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanelbarraLayout.setVerticalGroup(
            jPanelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 148, 770, 370));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gráfico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        jComboBoxGrafVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrafVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrafVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxGrafVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Veículo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ano:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jComboBoxGrafAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrafAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxGrafAnoMouseClicked(evt);
            }
        });
        getContentPane().add(jComboBoxGrafAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tipo do gasto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jComboBoxGrafTipoGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrafTipoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGrafTipoGastoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxGrafTipoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mês:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jComboBoxGrafMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGrafMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxGrafMesMouseClicked(evt);
            }
        });
        getContentPane().add(jComboBoxGrafMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGrafVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrafVeiculoActionPerformed
        // TODO add your handling code here:
        try {
            imprimirDadosNaComboBoxVeiculo(veiculoDao.listar());
        } catch (Exception erro) {
        }
    }//GEN-LAST:event_jComboBoxGrafVeiculoActionPerformed

    private void jComboBoxGrafTipoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGrafTipoGastoActionPerformed
        // TODO add your handling code here:
        try {
            imprimirDadosNaComboBoxTipoGasto(tipoGastosDao.listar());
        } catch (Exception erro) {
        }
    }//GEN-LAST:event_jComboBoxGrafTipoGastoActionPerformed

    private void jComboBoxGrafAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxGrafAnoMouseClicked
        // TODO add your handling code here:
        try {
            imprimirDadosNaComboBoxAno(gastosDao.listar());
        } catch (Exception erro) {
        }
    }//GEN-LAST:event_jComboBoxGrafAnoMouseClicked

    private void jComboBoxGrafMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxGrafMesMouseClicked
        // TODO add your handling code here:
        try {
            imprimirDadosNaComboBoxMes(gastosDao.listar());
        } catch (Exception erro) {
        }
    }//GEN-LAST:event_jComboBoxGrafMesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGrafAno;
    private javax.swing.JComboBox<String> jComboBoxGrafMes;
    private javax.swing.JComboBox<String> jComboBoxGrafTipoGasto;
    private javax.swing.JComboBox<String> jComboBoxGrafVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelbarra;
    // End of variables declaration//GEN-END:variables
}
